// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5ILoxsDcSHzOeJEaq-YRKVG49rVrc-6I',
    appId: '1:276291226018:web:ef98dc49141d6099218afb',
    messagingSenderId: '276291226018',
    projectId: 'chat-app-2580d',
    authDomain: 'chat-app-2580d.firebaseapp.com',
    storageBucket: 'chat-app-2580d.appspot.com',
    measurementId: 'G-9PG7K1ZF37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbFwWqzqG19bD8uIvO1aBUyBfKoHJMvvs',
    appId: '1:276291226018:android:e02f208b7ff89cbe218afb',
    messagingSenderId: '276291226018',
    projectId: 'chat-app-2580d',
    storageBucket: 'chat-app-2580d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAiIPGcComb4R_rgChVdCHmDbjFfRgvOU',
    appId: '1:276291226018:ios:81ca6f7a3cb527f6218afb',
    messagingSenderId: '276291226018',
    projectId: 'chat-app-2580d',
    storageBucket: 'chat-app-2580d.appspot.com',
    iosClientId: '276291226018-cr3c5ilpavg646cas3ltgaanr6t1crkj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAiIPGcComb4R_rgChVdCHmDbjFfRgvOU',
    appId: '1:276291226018:ios:81ca6f7a3cb527f6218afb',
    messagingSenderId: '276291226018',
    projectId: 'chat-app-2580d',
    storageBucket: 'chat-app-2580d.appspot.com',
    iosClientId: '276291226018-cr3c5ilpavg646cas3ltgaanr6t1crkj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
